name: meu_projeto_sqlite
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/seu_usuario/seu_repositorio

environment:
  sdk: ^3.5.4

dependencies:
  sqlite3: ^0.1.0
  sqflite: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
